### ISSUE TITLE
Class syntax

### ISSUE THREAD

**Issue by brandonchinn178** [calband/calchart-viewer#170]
@noahsark769 Javascript apparently supports a class syntax thats basically just syntactic sugar over inheritance and prototypes. It's supported on all the latest browsers (except IE?) but potentially not supported if people have older versions? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

I think it'd make the project a lot easier to dive into for people who may not be used to the prototype syntax. Thoughts?

**Comment by noahsark769** [comment]
@brandonchinn178 I would discourage against doing this. ES6 still has
limited support across browsers, and while I don't think we really need to
support internet explorer that much, I don't think it's s good idea to
totally shut IE out.

Secondly, I would worry that using class syntax would make it harder to
understand js's prototype system, which still exists regardless of syntax.

Thirdly, since there is not much development on the viewer right now, I
don't think we should change anything that doesn't need to be changed.

We can look into babeljs for support if we get more development going!

**Comment by brandonchinn178** [comment]
:+1: I think using babel when compiling with grunt would be perfect; we don't care about the output anyway. Maybe even minify the output?

**Comment by noahsark769** [comment]
Yeah, might as well minify it haha. The only thing about minifying is that you need an option to *not* minify, in case you want to debug something in the compiled output.

**Comment by brandonchinn178** [comment]
im sure grunt has an option for that

**Comment by noahsark769** [comment]
There's a plugin I believe :D
